
export default {
  ru: {
    i18nViewLogin: {
      title: 'Переключение языков',
      note: 'Интернационализация этого проекта основана на vue-i18n',
      datePlaceholder: 'Выбрать день',
      selectPlaceholder: 'Выбор',
      tableDate: 'tableDate',
      tableName: 'tableName',
      tableAddress: 'tableAddress',
      default: 'По умолчанию:',
      primary: 'Основной',
      success: 'Успешно',
      password_error: 'Пароль не прошол проверку',
      info: 'Иформация',
      warning: 'Внимание',
      danger: 'Опасность',
      one: 'Один',
      two: 'Два',
      three: 'Три',
      four: 'Четыре',
      language: 'Русский',
      ErrorValidateEmail: 'Пожалуйста, введите правильный адрес электронной почты',
      ErrorValidatePass: 'Пароль не может быть меньше 8 цифр',
    },
  },
  en: {
    i18nViewLogin: {
      title: 'Switch Language',
      note: 'The internationalization of this project is based on vue-i18n',
      datePlaceholder: 'Pick a day',
      selectPlaceholder: 'Select',
      tableDate: 'tableDate',
      tableName: 'tableName',
      tableAddress: 'tableAddress',
      default: 'default:',
      primary: 'primary',
      success: 'Success',
      password_error: 'Password failed verification',
      info: 'info',
      warning: 'warning',
      danger: 'danger',
      one: 'One',
      two: 'Two',
      three: 'Three',
      four: 'four',
      language: 'English',
      ErrorValidateEmail: 'Please enter a valid email address',
      ErrorValidatePass: 'Password cannot be less than 6 digits',
    },
  },
  vi: {
    i18nViewLogin: {
      title: 'Switch Language',
      note: 'The internationalization of this project is based on vue-i18n',
      datePlaceholder: 'Pick a day',
      selectPlaceholder: 'Select',
      tableDate: 'tableDate',
      tableName: 'tableName',
      tableAddress: 'tableAddress',
      default: 'mặc định:',
      primary: 'primary',
      success: 'thành công',
      password_error: 'Password failed verification',
      info: 'thông tin',
      warning: 'cảnh báo',
      danger: 'nguy hiểm',
      one: 'Một',
      two: 'Hai',
      three: 'Ba',
      four: 'bốn',
      language: 'Quan điểm',
      ErrorValidateEmail: 'Please enter a valid email address',
      ErrorValidatePass: 'Password cannot be less than 6 digits',
    },
  },
  zh: {
    i18nViewLogin: {
      title: '切换语言',
      note: '本项目国际化基于 vue-i18n',
      datePlaceholder: '请选择日期',
      selectPlaceholder: '请选择',
      tableDate: '日期',
      tableName: '姓名',
      tableAddress: '地址',
      default: '默认按钮',
      primary: '主要按钮',
      success: '成功按钮',
      password_error: 'Password failed verification',
      info: '信息按钮',
      warning: '警告按钮',
      danger: '危险按钮',
      one: '一',
      two: '二',
      three: '三',
      four: '四',
      language: '中国人',
      ErrorValidateEmail: 'Please enter a valid email address',
      ErrorValidatePass: 'Password cannot be less than 6 digits',
    },
  },
};
